# export_paper_tables.R
# Writes the tabular blocks build_paper_tables() assembles to paper/tables/<name>.tex, one file
# per table, plus paper/tables/auto_notes.tex holding one \newcommand per generated note
# sentence (docs/decisions/grade-report-response.md, item C1).
#
# Mirrors export_paper_figures.R in spirit: a flat named list whose names ARE the filenames
# paper/paper.tex hard-codes in its \input{tables/<name>.tex} lines, so renaming a key here
# breaks the LaTeX build loudly instead of silently pointing the paper at a stale table. Files
# are written as UTF-8 without a byte-order mark; the blocks themselves are ASCII.
export_paper_tables <- function(blocks, output_dir = file.path("paper", "tables")) {
  if (!is.list(blocks) || is.null(blocks$tables)) {
    stop("export_paper_tables: `blocks` must be the list build_paper_tables() returns ",
         "(with a `tables` element).")
  }
  if (!dir.exists(output_dir)) dir.create(output_dir, recursive = TRUE)

  written <- character(0)
  for (nm in names(blocks$tables)) {
    body <- blocks$tables[[nm]]
    if (!is.character(body) || length(body) == 0) {
      message("export_paper_tables: skipping '", nm, "' -- not a character vector.")
      next
    }
    file <- file.path(output_dir, paste0(nm, ".tex"))
    con <- file(file, open = "w", encoding = "UTF-8")
    writeLines(body, con)
    close(con)
    written <- c(written, file)
  }

  if (!is.null(blocks$notes) && length(blocks$notes) > 0) {
    notes <- blocks$notes
    if (is.null(names(notes)) || any(!nzchar(names(notes)))) {
      stop("export_paper_tables: every note must be named (the name becomes the LaTeX macro).")
    }
    bad <- grepl("[^A-Za-z]", names(notes))
    if (any(bad)) {
      stop("export_paper_tables: note names must be letters only (LaTeX macro names): ",
           paste(names(notes)[bad], collapse = ", "))
    }
    file <- file.path(output_dir, "auto_notes.tex")
    con <- file(file, open = "w", encoding = "UTF-8")
    writeLines(c(
      "% Generated by scripts/export_paper_tables.R from a pipeline run. Do not edit by hand.",
      sprintf("\\newcommand{\\%s}{%s}", names(notes), unname(notes))
    ), con)
    close(con)
    written <- c(written, file)
  }

  invisible(written)
}
